// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pro;

#nullable disable

namespace Pro.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20240728145822_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pro.Models.Categoria", b =>
                {
                    b.Property<Guid>("CodigoCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CodigoCategoria");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CodigoCategoria = new Guid("ee877ebe-14e2-4ad2-aa4f-bf4b5207657b"),
                            Descripcion = "",
                            Nombre = "Actividades pendientes",
                            Peso = 1
                        },
                        new
                        {
                            CodigoCategoria = new Guid("ee877ebe-14e2-4ad2-aa4f-bf4b52076502"),
                            Descripcion = "",
                            Nombre = "Actividades activas",
                            Peso = 2
                        });
                });

            modelBuilder.Entity("pro.Models.Tarea", b =>
                {
                    b.Property<Guid>("CodigoTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CodigoTarea");

                    b.HasIndex("CodigoCategoria");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            CodigoTarea = new Guid("ee877ebe-14e2-4ad2-aa4f-bf4b52076510"),
                            CodigoCategoria = new Guid("ee877ebe-14e2-4ad2-aa4f-bf4b5207657b"),
                            Descripcon = "",
                            FechaCreacion = new DateTime(2024, 7, 28, 8, 58, 22, 39, DateTimeKind.Local).AddTicks(1429),
                            PrioridadTarea = 1,
                            Titulo = "Pago servicios publico"
                        },
                        new
                        {
                            CodigoTarea = new Guid("ee877ebe-14e2-4ad2-aa4f-bf4b52076520"),
                            CodigoCategoria = new Guid("ee877ebe-14e2-4ad2-aa4f-bf4b5207657b"),
                            Descripcon = "",
                            FechaCreacion = new DateTime(2024, 7, 28, 8, 58, 22, 39, DateTimeKind.Local).AddTicks(1444),
                            PrioridadTarea = 2,
                            Titulo = "Pago servicios privados"
                        },
                        new
                        {
                            CodigoTarea = new Guid("ee877ebe-14e2-4ad2-aa4f-bf4b52076530"),
                            CodigoCategoria = new Guid("ee877ebe-14e2-4ad2-aa4f-bf4b52076502"),
                            Descripcon = "",
                            FechaCreacion = new DateTime(2024, 7, 28, 8, 58, 22, 39, DateTimeKind.Local).AddTicks(1447),
                            PrioridadTarea = 2,
                            Titulo = "Pago U"
                        });
                });

            modelBuilder.Entity("pro.Models.Tarea", b =>
                {
                    b.HasOne("pro.Models.Categoria", "Categorias")
                        .WithMany("Tareas")
                        .HasForeignKey("CodigoCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("pro.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
